name: CI/CD

on:
  pull_request:
    branches: [ master ]

jobs:
#  examples-builds:
#  eslint:
#  eslint-on-output:
  integration-tests:
    concurrency:
      group: integration-tests-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/727-ventures/openbrush-contracts-ci
      options: --user root
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: actions/checkout@v3
      - name: Yarn install dependencies
        run: |
          npm install
      - name: Run Test Mocha
        run: |
          set +e
          substrate-contracts-node --tmp --dev & P1=$!;
          set -e
          npm run test
          kill $P1
        timeout-minutes: 3